sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Administration
#    title_logo: 'images/favicon.ico'
#    options:
#        title_mode: single_text
    security:
        handler: admin.native_security_handler
    dashboard:
        blocks:
            -
                type: sonata.admin.block.admin_list
                position: left
                settings:
                    groups: [master_tables]
        groups:
            master_tables:
                label: Master Tables
                roles: [ROLE_SONATA_ADMIN]